services:
  admin-backend:
    restart: on-failure:10
    build: ./admin-backend/
    environment:
      - NODE_ENV=docker
      - DB_URL=mongodb://db:27017
      - DB_USERNAME=admin
      - DB_PASSWORD=3)R79ZP,:cv}r_5(
    ports:
      - 3002:80
  admin-panel:
    restart: on-failure:10
    build: ./admin-panel/
    ports:
      - 8080:80
    environment:
      - REACT_APP_API_URL=http://localhost:3001
  db:
    image: 'mongo'
    container_name: 'dashboard-mongo'
    ports:
     - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=dashboard
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=3)R79ZP,:cv}r_5(
    volumes:
      - mongo-volume:/data/db
  gateway:
    image: nginx
    restart: on-failure:10
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/nginx.conf

volumes:
  mongo-volume:

