services:
  backend:
    restart: on-failure:10
    image: redroddeck/dash-backend
    environment:
      - NODE_ENV=docker
      - TRELLO_APIKEY=${TRELLO_APIKEY}
      - TRELLO_TOKEN=${TRELLO_TOKEN}
    ports:
      - 80:80
  frontend:
    restart: on-failure:10
    image: redroddeck/dash
    ports:
      - 8080:80
    environment:
      - REACT_APP_TRELLO_URL=http://host.docker.internal

networks:
  internal:
