version: "3.9"
services:
  db:
    image: 'mongo'
    container_name: 'dashboard-mongo'
    ports:
     - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=dashboard
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=3)R79ZP,:cv}r_5(
    volumes:
      - mongo-volume:/data/db
  # gateway:
  #   image: nginx
  #   restart: on-failure:10
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #   volumes:
  #     - type: bind
  #       source: ./nginx/local.conf
  #       target: /etc/nginx/nginx.conf

volumes:
  mongo-volume:
